name: Build Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'grafana/loki'

      - name: Declare hash
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          ls && git rev-parse --short HEAD
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: n0vad3v
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: n0vad3v
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push latest images
        uses: docker/build-push-action@v5
        with:
          file: ./clients/cmd/fluent-bit/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            n0vad3v/fluent-bit-plugin-loki:main
            n0vad3v/fluent-bit-plugin-loki:main-${{ steps.vars.outputs.sha_short }}
            ghcr.io/n0vad3v/fluent-bit-plugin-loki:main-${{ steps.vars.outputs.sha_short }}
            ghcr.io/n0vad3v/fluent-bit-plugin-loki:main
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache